Repository cloudposse/terraform-provider-utils, pull requests merged in 2021-04, with the labels that each got.

#26 [stack_processor]: Read and parse only YAML files
  internal/stack/stack_processor.go
  internal/utils/file_utils.go
  internal/utils/string_utils.go
Labels: patch

#27 [stack_processor]: Add `process_stack_deps` input var to the `stack_config` data source
  README.md
  README.yaml
  examples/data-sources/utils_stack_config_yaml/data-source.tf
  internal/provider/data_source_stack_config_yaml.go
  internal/stack/stack_processor.go
  internal/stack/stack_processor_test.go
Labels: enhancement, go

#28 Fix target branch of workflow
  .github/workflows/auto-release.yml
Labels: no-release

#29 Use thread safe function
  internal/convert/id.go
Labels: bugfix
